apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend-user-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-backend-user
  template:
    metadata:
      labels:
        app: k8s-backend-user
    spec:
      containers:
        - name: k8s-backend-user
          image: surnavy/k8s-backend-user:0.0.8
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /backend/user/v1/k8s/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3

          readinessProbe:
            httpGet:
              path: /backend/user/v1/k8s/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 3

          volumeMounts:
            - mountPath: /etc/config
              name: backend-user-config-volume

      volumes:
        - name: backend-user-config-volume
          configMap:
            name: backend-user-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
